version: '3.1'

services:
  gitea:
    image: gitea/gitea:1.12.4
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - 8083:3000
      - 22:22
    depends_on:
      - db
    restart: always
