version: '3.1'

services:
  gitea:
    image: gitea/gitea:1.12.4
    environment:
          - USER_UID=1000
          - USER_GID=1000
#          - DB_TYPE=mysql
#          - DB_HOST=db:3306
#          - DB_NAME=gitea
#          - DB_USER=gitea
#          - DB_PASSWD=gitea
    ports:
      - 3000
      - 22:22
    depends_on:
      - db
    restart: always
